language: node_js
node_js: 8
dist: trusty
sudo: required
before_install:
- curl -u${ARTIFACTORY_USER}:${ARTIFACTORY_PASS} https://d2lartifacts.artifactoryonline.com/d2lartifacts/api/npm/attest/auth/attest > .npmrc
- npm i attest --registry=https://d2lartifacts.artifactoryonline.com/d2lartifacts/api/npm/attest/
- npm i
before_script:
- npm run test:lint
script:
- set -e
- npm run test:wct
- 'if [ "$TRAVIS_BRANCH" == "master" ]; then polymer test --skip-plugin local; fi'
- 'if [ "$TRAVIS_BRANCH" == "master" ]; then frauci-update-version; fi'
env:
  global:
  - REPO_NAME=d2l-save-status
  # GITHUB_RELEASE_TOKEN in CI Setting
  # SAUCE_USERNAME in CI Settting
  # SAUCE_ACCESS_KEY in CI Setting

addons:
  firefox: latest
  chrome: stable
  apt:
    packages:
    - gdebi
    - oracle-java9-installer
    - oracle-java9-set-default
